// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import inta "github.com/herlegs/GoTest/mockery"
import mock "github.com/stretchr/testify/mock"

// A is an autogenerated mock type for the A type
type A struct {
	mock.Mock
}

// GetB provides a mock function with given fields:
func (_m *A) GetB() inta.B {
	ret := _m.Called()

	var r0 inta.B
	if rf, ok := ret.Get(0).(func() inta.B); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(inta.B)
		}
	}

	return r0
}
